### ISSUE TITLE
Bug/error: impor template surat gagal 

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8462] opened 2024-09-11 03:31 UTC
### Jelaskan error yg dialami

impor template surat gagal

### Cara untuk mereplikasi errornya

1. pengaturan surat
2. impor template surat

### Hasil yg diharapkan

impor templat surat berhasil

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/4a76ee40-11d8-4423-b887-f5e509a82caa)

![image](https://github.com/user-attachments/assets/4e439f8d-4b51-4174-bbb3-e46c249a4c0d)

![image](https://github.com/user-attachments/assets/afa52962-ac45-45f4-80f0-481c7de12ab2)

![image](https://github.com/user-attachments/assets/38949ce0-0a24-4bb1-b7bd-826a9f9f11ac)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2409.0.0-premium

**Comment by andifahruddinakas** [comment] 2024-09-11 04:58
Duplicate of https://github.com/OpenSID/OpenSID/issues/8429

**Closed as completed by andifahruddinakas** 2024-09-11 04:58 UTC
Labels: bug
