### ISSUE TITLE
Bug/error: Costum Surat "Sulit Ngatur jarak atas bawah" => copy surat dari surat kuasa

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8189] opened 2024-07-12 03:59 UTC
### Jelaskan error yg dialami

edit templete susah..

![image](https://github.com/user-attachments/assets/e20ee65d-ccf4-4496-ab7f-39ebccccdf71)

### Cara untuk mereplikasi errornya

Copy surat dari surat kuasa >> buat surat baru dengan nama keterangan ahli waris..

### Hasil yg diharapkan

![image](https://github.com/user-attachments/assets/6755a12f-9f57-4954-916e-f313e36c64d4)

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/03206d9b-f46d-4e0d-8077-0055dcae1642)

![image](https://github.com/user-attachments/assets/4cc4139a-d45e-406e-be49-895185c557ee)

==========================================
lampiran

[a1ac7e4b-ce7c-4bf5-b128-1f3a1b07fee9.pdf](https://github.com/user-attachments/files/16188337/a1ac7e4b-ce7c-4bf5-b128-1f3a1b07fee9.pdf)

ini json suratnya..

[template_surat_tinymce_12_07_2024.json](https://github.com/user-attachments/files/16188352/template_surat_tinymce_12_07_2024.json)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.1

**Comment by andifahruddinakas** [comment] 2024-07-12 05:46
Duplicate of https://github.com/OpenSID/OpenSID/issues/8027

masih belum ketemu solusi teknisnya

**Closed as completed by andifahruddinakas** 2024-07-12 05:46 UTC
