### ISSUE TITLE
Bug/error: JABATAN PADA BAGAN ORGANISASI TIDAK SAMA DENGAN JABATAN PADA BUKU PEMERINTAHAN DESA

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#8830] opened 2024-12-22 02:34 UTC
### Jelaskan error yg dialami

SAAT JABATAN PJ. AKTIF. HASIL PADA BAGAN TETAP KEPALA DESA. YANG SEHARUSNYA MENGIKUTI JABATAN PJ. KEPALA DESA

### Cara untuk mereplikasi errornya

1. AKTIFKAN PJ. PADA KEPALA DESA
2. CETAK BAGAN ORGANISASI

### Hasil yg diharapkan

JABATAN YANG TERTULIS PADA BAGAN ORGAISASI SESUAI DENGAN YANG ADA DI BUKU PEMERINTAH DESA

### Tangkapan layar dan log error

PADA BUKU PEMERINTAH DESA
![Cuplikan layar 2024-12-22 092916](https://github.com/user-attachments/assets/c0d0fd38-96f5-4432-b7c4-f7d51da9303d)

PADA BAGAN ORGANISASI
![Cuplikan layar 2024-12-22 092853](https://github.com/user-attachments/assets/174c1eb0-0c2f-4aa3-8181-f842547593e6)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2412.0.2

**Comment by andifahruddinakas** [comment] 2024-12-22 23:40
Duplicate of https://github.com/OpenSID/OpenSID/issues/8829

**Closed as completed by andifahruddinakas** 2024-12-22 23:40 UTC
Labels: bug
