### ISSUE TITLE
Bug/error: IDM TIDAK TAMPIL MESKI SUMBER DATA DAPAT DIAKSES

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#8624] opened 2024-10-23 03:14 UTC
### Jelaskan error yg dialami

IDM TETAP TAMPIL 0 MESKI SUMBER DATA DAPAT DIAKSES

### Cara untuk mereplikasi errornya

1. INFO DESA
2. STATUS DESA
3. PILIH TAHUN
4. PERBARUI 

### Hasil yg diharapkan

NORMAL

### Tangkapan layar dan log error

![Cuplikan layar 2024-10-23 100601](https://github.com/user-attachments/assets/ce8940a4-0971-41dc-a276-888dcdcb4273)

SUMBER DATA
https://idm.kemendesa.go.id/open/api/desa/rumusan/7201102007/2024
![Cuplikan layar 2024-10-23 100538](https://github.com/user-attachments/assets/03de797e-6839-4840-9b0b-87b3ed2d416b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2410.0.2-premium

**Comment by andifahruddinakas** [comment] 2024-10-23 03:16
Duplicate of https://github.com/OpenSID/OpenSID/issues/8141

**Closed as completed by andifahruddinakas** 2024-10-23 03:16 UTC
Labels: bug
